### ISSUE TITLE
Cannot find module build/server.js

### ISSUE THREAD

**Issue by DrewCrop** [Bind/df-snarker#1]
Ubuntu 20.04.1 LTS server
npm -v: 6.14.10
node -v: v14.15.4
yarn -v: 1.22.10

yarn run start

yarn run v1.22.10
$ node build/server.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/home/miner/df-snarker/build/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
error Command failed with exit code 1.

**Comment by superphiz** [comment]
It looks like you're missing some dependencies (most likely node-typescript). I created an installation guide here: #2
