### ISSUE TITLE
TypeError: LRUMap is not a constructor

### ISSUE THREAD

**Issue by omarish** [Bind/df-snarker#3]
Hi,

I'm trying to run this locally via the `Dockerfile` and run into `TypeError: LRUMap is not a constructor`. I can dig in and figure out what's going on, but submitting this in case you know of an easy fix.

## Steps to reproduce:

```sh
docker build -t snarker:latest .
docker run snarker:latest
```

## Stack Trace:

```
❯ docker run snarker:latest

> df-snarker@1.0.0 start /usr/src/app
> node build/server.js

/usr/src/app/build/src/main.js:45
var InMemoryCache = new LRUMap(CACHE_SIZE);
                    ^

TypeError: LRUMap is not a constructor
    at Object.<anonymous> (/usr/src/app/build/src/main.js:45:21)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/src/app/build/server.js:43:30)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
```

**Comment by Bind** [comment]
Hey @omarish thank you for the issue and the corresponding PR!
